#!/bin/sh
### BEGIN INIT INFO
# Provides:          dnsproxyserver
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Start/stop dnsproxyserver server
### END INIT INFO
case $1 in
	start)
		/usr/sbin/dnsproxyserver
	;;
	stop)
		if [ -r /var/run/dnsproxyserver.pid ]
		then
			kill -2 `cat /var/run/dnsproxyserver.pid`
			sleep 2
			ps aux | grep dnsproxyserver && killall dnsproxyserver
		else
			killall dnsproxyserver
		fi
	;;
	restart)
		if [ -r /var/run/dnsproxyserver.pid ]
		then
			kill -1 `cat /var/run/dnsproxyserver.pid`
		else
			killall dnsproxyserver
			/usr/sbin/dnsproxyserver
		
		fi

	;;
esac
